import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

def send_daily_digest(user_email, user_name, articles):
    if not SENDER_EMAIL or not SENDER_PASSWORD:
        print("Error: Email credentials missing in .env")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Your Daily SmartBrief Digest, {user_name} 🧠"
    msg["From"] = SENDER_EMAIL
    msg["To"] = user_email

    html_content = f"""
    <html>
        <body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto;">
            <h2 style="color: #2c3e50;">Good morning, {user_name}!</h2>
            <p>Here is your personalized knowledge digest based on your interests:</p>
            <hr style="border: 1px solid #eee;">
    """

    for article in articles:
        html_content += f"""
            <h3 style="color: #0056b3; margin-bottom: 5px;">{article.get('title', 'Headline')}</h3>
            <p style="font-size: 14px; line-height: 1.5;">{article.get('summary', '')}</p>
            <a href="{article.get('url', '#')}" style="background-color: #28a745; color: white; padding: 8px 12px; text-decoration: none; border-radius: 4px; font-size: 12px; display: inline-block;">Read Full Article</a>
            <br><br><hr style="border: 1px solid #eee;">
        """

    html_content += """
            <p style="font-size: 11px; color: #999; text-align: center;">Automatically generated by your SmartBrief AI Pipeline</p>
        </body>
    </html>
    """

    msg.attach(MIMEText(html_content, "html"))

    try:
        print(f"Connecting to SMTP server to email {user_email}...")
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, user_email, msg.as_string())
        server.quit()
        
        print("✅ Email sent successfully!")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False